# Title in header
title: "雪、無音、窓辺にて。"

# INFO
# Owner info
owner: ""
info: "暖かい日差しを受けて　桃色の花びらが　飛び"
# Description, will be displayed at second line
desc: "舞い散る雪の季節がまた　終わりを告げる　妖精よ　ふらふらり　現れてくる"

# Main page top menu bar
menu:
  Archives: /archives
  Playground: ../play
  Externals: /external
  PGP Key: https://pgp.yukimuon.com
  .ME: /about

# Index/main page max show posts (in number)
max_post: 5

# Colors for links and top nanobar, use hex color without #
tcolor: ff6f61
ncolor: ffb7c5
lighttheme_color: ededed

# Social profile at the footer/bottom, default close
profile: false
place: 
github: 
instagram: 
twitter: 
date: false

# Misc
nanobar: /js/nanobar.min.js
switch: ☀️


# Favicon
favicon: /images/favicon.png

article:
  thumbnail: false

# DISQUS comments (sign up to Disqus to get disqus_shortname). default close
disqus_enabled: false
disqus_shortname:
